import { IResponse } from '../types/interfaces/mock-response.interface';

export const mockResponse: IResponse = {
  items: [
    {
      firstName: 'John',
      lastName: 'Doe',
      age: 20,
      email: 'john.doe@example.com',
      birthDate: new Date('2003-01-01'),
      subjectId: 101,
    },
    {
      firstName: 'Jane',
      lastName: 'Smith',
      age: 22,
      email: 'jane.smith@example.com',
      birthDate: new Date('2001-02-15'),
      subjectId: 102,
    },
    {
      firstName: 'Alice',
      lastName: 'Johnson',
      age: 21,
      email: 'alice.johnson@example.com',
      birthDate: new Date('2002-03-22'),
      subjectId: 103,
    },
    {
      firstName: 'Bob',
      lastName: 'Brown',
      age: 23,
      email: 'bob.brown@example.com',
      birthDate: new Date('2000-04-10'),
      subjectId: 104,
    },
    {
      firstName: 'Charlie',
      lastName: 'Davis',
      age: 20,
      email: 'charlie.davis@example.com',
      birthDate: new Date('2003-05-05'),
      subjectId: 105,
    },
    {
      firstName: 'Daisy',
      lastName: 'Miller',
      age: 19,
      email: 'daisy.miller@example.com',
      birthDate: new Date('2004-06-16'),
      subjectId: 106,
    },
    {
      firstName: 'Ella',
      lastName: 'Wilson',
      age: 21,
      email: 'ella.wilson@example.com',
      birthDate: new Date('2002-07-24'),
      subjectId: 107,
    },
    {
      firstName: 'George',
      lastName: 'Moore',
      age: 22,
      email: 'george.moore@example.com',
      birthDate: new Date('2001-08-30'),
      subjectId: 108,
    },
    {
      firstName: 'Hannah',
      lastName: 'Taylor',
      age: 20,
      email: 'hannah.taylor@example.com',
      birthDate: new Date('2003-09-14'),
      subjectId: 109,
    },
    {
      firstName: 'Ian',
      lastName: 'Anderson',
      age: 19,
      email: 'ian.anderson@example.com',
      birthDate: new Date('2004-10-28'),
      subjectId: 110,
    },
  ],
  total: 10,
};
